name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        ports: ['3306:3306']
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
        env:
          MYSQL_ROOT_PASSWORD: Ten@2106
          MYSQL_DATABASE: systempharm

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven Packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
          
      - name: Install Dependencies
        working-directory: systempharm
        run: mvn install --no-transfer-progress

      - name: Run Tests
        working-directory: systempharm
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/systempharm
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: Ten@2106
        run: mvn test